//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WibaReport.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Claim()
        {
            this.Appointments = new HashSet<Appointment>();
            this.ClaimDocuments = new HashSet<ClaimDocument>();
        }
    
        public System.Guid Id { get; set; }
        public int RecordStatus { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public System.Guid MemberId { get; set; }
        public System.Guid ClaimSourceId { get; set; }
        public byte ClaimType { get; set; }
        public string LenghtOfService { get; set; }
        public string EmployeeDuties { get; set; }
        public byte IsApprovedByHk { get; set; }
        public byte IsApprovedByDosh { get; set; }
        public byte IsApprovedByMakl { get; set; }
        public byte IsApprovedByNhif { get; set; }
        public byte IsApprovedByEmployer { get; set; }
        public byte IsApprovedByHospital { get; set; }
        public string HkComment { get; set; }
        public string DoshComment { get; set; }
        public string MaklComment { get; set; }
        public string NhifComment { get; set; }
        public string EmployerComment { get; set; }
        public string EmployerRejectReason { get; set; }
        public string HkRejectReason { get; set; }
        public long ClaimNumber { get; set; }
        public string HospitalName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaimDocument> ClaimDocuments { get; set; }
        public virtual Member Member { get; set; }
    }
}
