//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WibaReport.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinic
    {
        public long Pkid { get; set; }
        public string Name { get; set; }
        public long Region { get; set; }
        public long County { get; set; }
        public long SubCounty { get; set; }
        public string Address { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string WebsiteUrl { get; set; }
        public string OpeningHours { get; set; }
        public string Category { get; set; }
    }
}
