//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WibaReport.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class County
    {
        public long PKID { get; set; }
        public Nullable<long> Code { get; set; }
        public string CountyName { get; set; }
        public string FormerProvince { get; set; }
        public Nullable<long> RegionID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CountyCoordinates { get; set; }
    }
}
