//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WibaReport.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        public System.Guid Id { get; set; }
        public int RecordStatus { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string FullName { get; set; }
        public string RegistrationNumber { get; set; }
        public string FullAddress { get; set; }
        public string Industry { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public System.Guid InsuranceId { get; set; }
    }
}
