//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WibaReport.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalReport
    {
        public System.Guid Id { get; set; }
        public int RecordStatus { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public System.Guid AppointmentId { get; set; }
        public System.Guid MemberId { get; set; }
        public System.Guid ClaimId { get; set; }
        public string TypeOfInjury { get; set; }
        public System.DateTime DateOfAdmission { get; set; }
        public bool IsDischarged { get; set; }
        public string OccupationalDisease { get; set; }
        public string InpatientNumber { get; set; }
        public bool IspermanentIncapacity { get; set; }
        public string PermanentIncapacityDetails { get; set; }
        public string PercentageOfpermanentIncapacity { get; set; }
        public bool IsfurtherExaminationRequired { get; set; }
        public string Examination { get; set; }
        public System.DateTime DateOfExamination { get; set; }
        public string medicalPractitioner { get; set; }
        public string HospitalName { get; set; }
        public string TemporaryIncapacity { get; set; }
    }
}
