//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WibaReport.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberEarning
    {
        public System.Guid Id { get; set; }
        public int RecordStatus { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public decimal CashWage { get; set; }
        public decimal ValueOfRations { get; set; }
        public decimal valueOfHousing { get; set; }
        public decimal valueOfFuel { get; set; }
        public decimal Allowances { get; set; }
        public decimal OtherRenumerations { get; set; }
        public decimal TotalEarnings { get; set; }
        public string HasResumedWork { get; set; }
        public Nullable<System.DateTime> DateOfResumption { get; set; }
        public string LengthOfService { get; set; }
        public System.Guid MemberId { get; set; }
        public string Remarks { get; set; }
    }
}
