//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WibaReport.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Claims = new HashSet<Claim>();
        }
    
        public System.Guid Id { get; set; }
        public int RecordStatus { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string IDNumber { get; set; }
        public string Email { get; set; }
        public string MemberNumber { get; set; }
        public string EmployeeNumber { get; set; }
        public string NhifNumber { get; set; }
        public string Relationship { get; set; }
        public string Gender { get; set; }
        public string Occupation { get; set; }
        public string CountyOfResident { get; set; }
        public string SubCountyOfResident { get; set; }
        public bool IsPrincipal { get; set; }
        public string Password { get; set; }
        public string PIN { get; set; }
        public System.Guid EmployerId { get; set; }
        public Nullable<int> RoldeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Claim> Claims { get; set; }
    }
}
