//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WibaReport.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WibaERPProdEntities : DbContext
    {
        public WibaERPProdEntities()
            : base("name=WibaERPProdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<ClaimDocument> ClaimDocuments { get; set; }
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<Clinic> Clinics { get; set; }
        public virtual DbSet<County> Counties { get; set; }
        public virtual DbSet<Employer> Employers { get; set; }
        public virtual DbSet<InsuranceProvider> InsuranceProviders { get; set; }
        public virtual DbSet<LastExpenseClaim> LastExpenseClaims { get; set; }
        public virtual DbSet<MedicalReport> MedicalReports { get; set; }
        public virtual DbSet<MemberEarning> MemberEarnings { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<OccupationalDiseaseClaim> OccupationalDiseaseClaims { get; set; }
        public virtual DbSet<OccupationalInjuryClaim> OccupationalInjuryClaims { get; set; }
        public virtual DbSet<OtherMemberClaimsToClaimMapping> OtherMemberClaimsToClaimMappings { get; set; }
        public virtual DbSet<OtherMembersClaim> OtherMembersClaims { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
