//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WibaReport.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupationalInjuryClaim
    {
        public System.Guid Id { get; set; }
        public int RecordStatus { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public System.DateTime DateOfAccident { get; set; }
        public System.DateTime TimeOfAccident { get; set; }
        public Nullable<bool> HasResumedWork { get; set; }
        public System.DateTime DateOfResumption { get; set; }
        public string PlaceOfAccident { get; set; }
        public string CauseOfInjury { get; set; }
        public byte TypeOfInjury { get; set; }
        public string PartOfBodyInjured { get; set; }
    }
}
